---
- hosts: redhatos
  become: yes
  tasks:
  - name: execte linux commmand
    command: hostname -f
    register: myresult
  - name: display the myresult 
    debug: 
       msg: "{{myresult}}"

  - name: install git
    yum:
      name: git
    when: myresult.stderr ==""

  - name: install tree
    yum:
      name: tree
    when: myresult.stderr !=""