---
- hosts: redhatos
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on redhat
    yum:
      name: httpd
    notify: startwebserver


  - name: copy index.html into webserver
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: startwebserver
 


  handlers:
  - name: startwebserver
    service:
      name: httpd
      state: started  

