---
- hosts: webservers
  become: yes
  tasks: 
  - name: install webserver on ubuntu(apache2)
    apt:
      name: "{{webserveronubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: service start  on ubuntu(apache2)
    service:
      name: "{{webserveronubuntu}}"
      state: started
    when: ansible_os_family =="Debian"

  - name: install webserver on redhat(httpd)
    yum:
      name: "{{webserveronredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
        
  - name: service start on redhat(httpd)
    service:
      name: "{{webserveronredhat}}"
      state: started
    when: ansible_os_family =="RedHat"

   