---
# tasks file for mytominstallrole
- name: install tomcat
  yum:
    name: tomcat
    state: present

- name: copy tom config file into nodes
  template:
    src: templates/tomcofig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
- name: install admin pak
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps

- name: copy tom user file into nodes
  template:
    src: templates/tomuser.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: starttomcat
  

- name: deploy mahalogin java application on tomcat webapps folder
  get_url:
    url: https://s3-ap-southeast-1.amazonaws.com/mypem04056/MAHALogin.war
    dest: /usr/share/tomcat/webapps/
    force_basic_auth: yes
  notify: restarttomcat

